//  export const PRODUCTS =[
//     {
//         id:1,
//         price : 2000.00,
//         productImage: "https://m.media-amazon.com/images/I/716kSfEScGS._SY695_.jpg",
//         productdescription: "CasualCanvasSneakers",
//         category:"men",
//     },
//     {
//         id:2,
//         price : 3000.00,
//         productImage:   "https://m.media-amazon.com/images/I/619pdY6a6JL._SY695_.jpg" ,
//         productdescription: "RunningShoes",
//         category:"men",
//       },
//       {
//         id:3,
//         price : 1500.00,
//         productImage:   "https://m.media-amazon.com/images/I/71QobNwcYxS._SY695_.jpg" ,
//         productdescription: "ChunkySneakers",
//         category:"men",
//       },
//       {
//         id:4,
//         price : 1000.00,
//         productImage: "https://m.media-amazon.com/images/I/71LSwmlC2kL._SY695_.jpg" ,
//         productdescription: "OxfordSneakers",
//         category:"men",
//       },
//       {
//         id:5,
//         price : 5000.00,
//         productImage:"https://m.media-amazon.com/images/I/71NQrTFXdZL._SY695_.jpg" ,
//         productdescription:" LeatherBoots",
//         category:"women",
//       },
//       {
//         id:6,
//         price : 6000.00,
//         productImage:"https://m.media-amazon.com/images/I/71fa6RbVRaL._SY695_.jpg",
//         productdescription: "FurBoots",
//         category:"women",
//       },
//       {
//         id:7,
//         price : 7500.00,
//         productImage:"https://m.media-amazon.com/images/I/81+ud2XUg7L._SY695_.jpg" ,
//         productdescription:" Snowboots",
//         category:"women",
//       },
//       {
//         id:8,
//         price : 8000.00,
//         productImage:"https://m.media-amazon.com/images/I/71KrFpB0JXL._SY695_.jpg" ,
//         productdescription:" NeonBoots",
//         category:"women",
//       },
// ];